apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zavq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0070-tenant/ci10t-776-0070-app/devfile-sample-zavq@sha256:0677be5d9c9c26c8fbb7ce4192e8c7ea731db6a630eeab9a0c03bf927158dc7f
        name: my-nodejs
        resources: {}
status: {}
